[package]
name = "encoding"
version = "0.1.0"
authors = ["yukimemi <yukimemi@gmail.com>"]
edition = "2018"

[dependencies]
encoding_rs_io = "0.1.6"
csv = "1.0.7"
failure = "0.1.5"
pretty_env_logger = "0.3.0"
log = "0.4.6"
clap = "2.33.0"
