[config]
skip_core_tasks = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.rebuild]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.install]
command = "cargo"
args = ["install", "--force", "--path", "."]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--nocapture"]
dependencies = ["lint"]

[tasks.debug]
script = ["RUST_LOG=encoding=debug cargo run -- ${@}"]

[tasks.watch]
env = { "RUST_LOG" = "encoding=debug" }
watch = { postpone = true, ignore_pattern = "dst/*" }
dependencies = [
  "build",
  "test",
]


[tasks.default]
dependencies = [
  "format",
  "build",
  "test",
]

